name: Build and Deploy Angular to Versioned GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.read.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract package version
        id: read
        uses: zvonimirsun/read-package-version-actions@v2

  build-and-deploy:
    needs: read-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Set Deployment Variables
        id: vars
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          APP_VERSION="${{ needs.read-version.outputs.app_version }}"
          BASE_HREF="/$REPO_NAME/$APP_VERSION/"
          BUILD_OUTPUT_DIR="./build_output"
          echo "BASE_HREF=$BASE_HREF" >> $GITHUB_ENV
          echo "BUILD_OUTPUT_DIR=$BUILD_OUTPUT_DIR" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app with versioned base-href
        run: npm run build -- --output-path=${{ env.BUILD_OUTPUT_DIR }} --base-href=${{ env.BASE_HREF }}

      - name: Deploy to gh-pages branch with versioned folder
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_OUTPUT_DIR }}
          destination_dir: ${{ needs.read-version.outputs.app_version }}
          keep_files: true
