name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  read-version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.read.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Extract package version
        id: read
        uses: zvonimirsun/read-package-version-actions@v2

  deploy:
    needs: read-version
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm" # Recommended for faster installs

      - name: Set deployment path
        id: vars
        run: |
          DEPLOY_PATH="dist/${{ github.event.repository.name }}/${{ needs.read-version.outputs.app_version }}"
          echo "DEPLOY_PATH=$DEPLOY_PATH" >> $GITHUB_ENV
          echo "deploy_path_url=/url/${{ needs.read-version.outputs.app_version }}" >> $GITHUB_ENV

      - name: Build and Publish to GitHub Pages
        id: build-publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          # Use the dynamic base-href and path for cache busting
          path: ${{ env.DEPLOY_PATH }}
          # The install and build commands can be customized here
          install_command: npm ci
          build_command: npm run build -- --base-href=/${{ github.event.repository.name }}/${{ needs.read-version.outputs.app_version }}/
          caching: true # Enable npm dependency caching for faster runs
